export const PASSWORD_RESET_OTP_LENGTH = 6;
export const PASSWORD_RESET_OTP_TTL_MINUTES = 10;
export const MAX_PASSWORD_RESET_OTP_ATTEMPTS = 5;

export const PASSWORD_RESET_OTP_MIN = 10 ** (PASSWORD_RESET_OTP_LENGTH - 1);
export const PASSWORD_RESET_OTP_MAX_EXCLUSIVE = 10 ** PASSWORD_RESET_OTP_LENGTH;
